const data =
    [
        { "name": "Tomato", "type": "vegetable" },
        { "name": "Cucumber", "type": "vegetable" },
        { "name": "Carrot", "type": "vegetable" },
        { "name": "Onion", "type": "vegetable" },
        { "name": "Bell Pepper", "type": "vegetable" },
        { "name": "Garlic", "type": "vegetable" },
        { "name": "Potato", "type": "vegetable" },
        { "name": "Broccoli", "type": "vegetable" },
        { "name": "Spinach", "type": "vegetable" },
        { "name": "Zucchini", "type": "vegetable" },
        { "name": "Lettuce", "type": "vegetable" },
        { "name": "Celery", "type": "vegetable" },
        { "name": "Eggplant", "type": "vegetable" },
        { "name": "Mushroom", "type": "vegetable" },
        { "name": "Peas", "type": "vegetable" },
        { "name": "Corn", "type": "vegetable" },
        { "name": "Beetroot", "type": "vegetable" },
        { "name": "Cabbage", "type": "vegetable" },
        { "name": "Cauliflower", "type": "vegetable" },
        { "name": "Asparagus", "type": "vegetable" },
        { "name": "Radish", "type": "vegetable" },
        { "name": "Brussels Sprouts", "type": "vegetable" },
        { "name": "Kale", "type": "vegetable" },
        { "name": "Leek", "type": "vegetable" },
        { "name": "Artichoke", "type": "vegetable" },
        { "name": "Okra", "type": "vegetable" },

        { "name": "Chicken", "type": "meat" },
        { "name": "Beef", "type": "meat" },
        { "name": "Pork", "type": "meat" },
        { "name": "Lamb", "type": "meat" },
        { "name": "Turkey", "type": "meat" },
        { "name": "Duck", "type": "meat" },
        { "name": "Fish", "type": "meat" },
        { "name": "Salmon", "type": "meat" },
        { "name": "Shrimp", "type": "meat" },
        { "name": "Crab", "type": "meat" },
        { "name": "Lobster", "type": "meat" },
        { "name": "Bacon", "type": "meat" },
        { "name": "Sausage", "type": "meat" },
        { "name": "Ham", "type": "meat" },
        { "name": "Veal", "type": "meat" },
        { "name": "Venison", "type": "meat" },
        { "name": "Goose", "type": "meat" },
        { "name": "Quail", "type": "meat" },

        { "name": "Apple", "type": "fruit" },
        { "name": "Banana", "type": "fruit" },
        { "name": "Orange", "type": "fruit" },
        { "name": "Lemon", "type": "fruit" },
        { "name": "Strawberry", "type": "fruit" },
        { "name": "Blueberry", "type": "fruit" },
        { "name": "Grapes", "type": "fruit" },
        { "name": "Pineapple", "type": "fruit" },
        { "name": "Mango", "type": "fruit" },
        { "name": "Avocado", "type": "fruit" },
        { "name": "Pear", "type": "fruit" },
        { "name": "Peach", "type": "fruit" },
        { "name": "Plum", "type": "fruit" },
        { "name": "Watermelon", "type": "fruit" },
        { "name": "Melon", "type": "fruit" },
        { "name": "Cherry", "type": "fruit" },
        { "name": "Kiwi", "type": "fruit" },
        { "name": "Papaya", "type": "fruit" },
        { "name": "Fig", "type": "fruit" },
        { "name": "Pomegranate", "type": "fruit" },
        { "name": "Guava", "type": "fruit" },
        { "name": "Coconut", "type": "fruit" },
        { "name": "Lime", "type": "fruit" },

        { "name": "Milk", "type": "dairy" },
        { "name": "Cheese", "type": "dairy" },
        { "name": "Yogurt", "type": "dairy" },
        { "name": "Butter", "type": "dairy" },
        { "name": "Cream", "type": "dairy" },
        { "name": "Cottage Cheese", "type": "dairy" },
        { "name": "Sour Cream", "type": "dairy" },
        { "name": "Ghee", "type": "dairy" },
        { "name": "Buttermilk", "type": "dairy" },
        { "name": "Ricotta", "type": "dairy" },
        { "name": "Mozzarella", "type": "dairy" },
        { "name": "Parmesan", "type": "dairy" },
        { "name": "Feta", "type": "dairy" },
        { "name": "Cream Cheese", "type": "dairy" },
        { "name": "Mascarpone", "type": "dairy" },

        { "name": "Lentil", "type": "legume" },
        { "name": "Chickpea", "type": "legume" },
        { "name": "Black Beans", "type": "legume" },
        { "name": "Kidney Beans", "type": "legume" },
        { "name": "Green Beans", "type": "legume" },
        { "name": "Soybeans", "type": "legume" },
        { "name": "Peanuts", "type": "legume" },
        { "name": "Navy Beans", "type": "legume" },
        { "name": "Pinto Beans", "type": "legume" },
        { "name": "Red Lentils", "type": "legume" },
        { "name": "Mung Beans", "type": "legume" },

        { "name": "Rice", "type": "grain" },
        { "name": "Quinoa", "type": "grain" },
        { "name": "Wheat", "type": "grain" },
        { "name": "Oats", "type": "grain" },
        { "name": "Barley", "type": "grain" },
        { "name": "Couscous", "type": "grain" },
        { "name": "Bulgur", "type": "grain" },
        { "name": "Pasta", "type": "grain" },
        { "name": "Buckwheat", "type": "grain" },
        { "name": "Millet", "type": "grain" },
        { "name": "Rye", "type": "grain" },
        { "name": "Sorghum", "type": "grain" },

        { "name": "Olive Oil", "type": "oil" },
        { "name": "Coconut Oil", "type": "oil" },
        { "name": "Vegetable Oil", "type": "oil" },
        { "name": "Butter", "type": "oil" },
        { "name": "Canola Oil", "type": "oil" },
        { "name": "Sesame Oil", "type": "oil" },
        { "name": "Sunflower Oil", "type": "oil" },
        { "name": "Peanut Oil", "type": "oil" },
        { "name": "Avocado Oil", "type": "oil" },
        { "name": "Flaxseed Oil", "type": "oil" },
        { "name": "Grapeseed Oil", "type": "oil" },

        { "name": "Salt", "type": "spice" },
        { "name": "Black Pepper", "type": "spice" },
        { "name": "Paprika", "type": "spice" },
        { "name": "Cumin", "type": "spice" },
        { "name": "Cinnamon", "type": "spice" },
        { "name": "Coriander", "type": "spice" },
        { "name": "Ginger", "type": "spice" },
        { "name": "Turmeric", "type": "spice" },
        { "name": "Chili Powder", "type": "spice" },
        { "name": "Oregano", "type": "spice" },
        { "name": "Basil", "type": "spice" },
        { "name": "Thyme", "type": "spice" },
        { "name": "Rosemary", "type": "spice" },
        { "name": "Nutmeg", "type": "spice" },
        { "name": "Cloves", "type": "spice" },
        { "name": "Cardamom", "type": "spice" },
        { "name": "Saffron", "type": "spice" },
        { "name": "Bay Leaves", "type": "spice" },
        { "name": "Mustard Seeds", "type": "spice" }
    ];

export default data;


export const types = [
    'vegetable', 'meat', 'fruit', 'spice', 'oil', 'grain', 'legume', 'dairy'
];